version: '3.4'

services:
  pythonprogram:
    image: pythonprogram
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 5day403/Pseudo-binary numbers/Pseudo-binary numbers.py "]
    ports:
      - 5678:5678
